I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 202, in script
    scene bg room with shake
  File "game/script.rpy", line 202, in <module>
    scene bg room with shake
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 202, in script
    scene bg room with shake
  File "/Users/ichigo/Desktop/Macbook Backup 2/Code/renpy-6.99.12.4-sdk/renpy/ast.py", line 1271, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Users/ichigo/Desktop/Macbook Backup 2/Code/renpy-6.99.12.4-sdk/renpy/python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/ichigo/Desktop/Macbook Backup 2/Code/renpy-6.99.12.4-sdk/renpy/python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 202, in <module>
    scene bg room with shake
NameError: name 'flash' is not defined

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Test Project! 1.0
